[package]
name = "rslogo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unsvg = "1.1.1"
clap = { version = "4.5.2", features = ["derive"] }
lib_crate = { path = "../lib_crate"}